teams:
  Africa do Sul: África do Sul
  Algeria: Argélia
  Argentina: Argentina
  Australia: Austrália
  Austria: Áustria
  Belgium: Bélgica
  Bosnia and Herzegovina: Bósnia e Herzegovina
  Bosnia-Herzegovina: Bósnia e Herzegovina
  Brazil: Brasil
  Canada: Canadá
  Cape Verde: Cabo Verde
  Colombia: Colômbia
  Croatia: Croácia
  Curaçao: Curaçao
  Czech Republic: Tchéquia
  Czechia: Tchéquia
  Czech Rep.: Tchéquia
  DR Congo: RD Congo
  Congo DR: RD Congo
  Democratic Republic of the Congo: RD Congo
  Ecuador: Equador
  Egypt: Egito
  England: Inglaterra
  France: França
  Germany: Alemanha
  Ghana: Gana
  Haiti: Haiti
  Iran: Irã
  IR Iran: Irã
  Iraq: Iraque
  Ivory Coast: Costa do Marfim
  "Côte d'Ivoire": Costa do Marfim
  "Cote d'Ivoire": Costa do Marfim
  Japan: Japão
  Jordan: Jordânia
  Korea Republic: Coreia do Sul
  Mexico: México
  Morocco: Marrocos
  Netherlands: Países Baixos
  Holland: Países Baixos
  New Zealand: Nova Zelândia
  Norway: Noruega
  Panama: Panamá
  Paraguay: Paraguai
  Portugal: Portugal
  Qatar: Catar
  Saudi Arabia: Arábia Saudita
  Scotland: Escócia
  Senegal: Senegal
  South Africa: África do Sul
  South Korea: Coreia do Sul
  Spain: Espanha
  Sweden: Suécia
  Switzerland: Suíça
  Tunisia: Tunísia
  Turkey: Turquia
  Turkiye: Turquia
  Türkiye: Turquia
  Uruguay: Uruguai
  USA: Estados Unidos
  United States: Estados Unidos
  Uzbekistan: Uzbequistão
